/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.visao;

import br.com.controle.Calculos;

/**
 *
 * @author pedro.jovino
 */
public class Tela1 extends javax.swing.JFrame {
    Calculos calculos = new Calculos();

    /**
     * Creates new form Tela1
     */
    public Tela1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTvalor1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTvalor2 = new javax.swing.JTextField();
        jBsomar = new javax.swing.JButton();
        jLresultado = new javax.swing.JLabel();
        jBsubtrair = new javax.swing.JButton();
        jBmultiplicar = new javax.swing.JButton();
        jBdividir = new javax.swing.JButton();
        jBporcentagem = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Digite o valor 1");

        jLabel2.setText("Digite o valor 2");

        jBsomar.setText("+");
        jBsomar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsomarActionPerformed(evt);
            }
        });

        jLresultado.setText("0.00");

        jBsubtrair.setText("-");
        jBsubtrair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsubtrairActionPerformed(evt);
            }
        });

        jBmultiplicar.setText("*");
        jBmultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBmultiplicarActionPerformed(evt);
            }
        });

        jBdividir.setText("/");
        jBdividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBdividirActionPerformed(evt);
            }
        });

        jBporcentagem.setText("%");
        jBporcentagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBporcentagemActionPerformed(evt);
            }
        });

        jLabel3.setText("Total:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(153, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jTvalor2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTvalor1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLresultado))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBsomar)
                                .addGap(18, 18, 18)
                                .addComponent(jBsubtrair)
                                .addGap(18, 18, 18)
                                .addComponent(jBmultiplicar)))
                        .addGap(18, 18, 18)
                        .addComponent(jBdividir)
                        .addGap(18, 18, 18)
                        .addComponent(jBporcentagem)))
                .addGap(156, 156, 156))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTvalor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTvalor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBmultiplicar)
                    .addComponent(jBsubtrair)
                    .addComponent(jBsomar)
                    .addComponent(jBdividir)
                    .addComponent(jBporcentagem))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLresultado)
                    .addComponent(jLabel3))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBsomarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsomarActionPerformed
        // TODO add your handling code here:
        calculos.setValor1(Double.valueOf(jTvalor1.getText()));
         calculos.setValor2(Double.valueOf(jTvalor2.getText()));
         jLresultado.setText("" + calculos.somar());
    }//GEN-LAST:event_jBsomarActionPerformed

    private void jBmultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBmultiplicarActionPerformed
        // TODO add your handling code here:
        calculos.setValor1(Double.valueOf(jTvalor1.getText()));
        calculos.setValor2(Double.valueOf(jTvalor2.getText()));
        jLresultado.setText("" + calculos.multiplicar());
    }//GEN-LAST:event_jBmultiplicarActionPerformed

    private void jBsubtrairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsubtrairActionPerformed
        // TODO add your handling code here:
        calculos.setValor1(Double.valueOf(jTvalor1.getText()));
        calculos.setValor2(Double.valueOf(jTvalor2.getText()));
        jLresultado.setText("" + calculos.subtrair());
    }//GEN-LAST:event_jBsubtrairActionPerformed

    private void jBdividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBdividirActionPerformed
        // TODO add your handling code here:
        calculos.setValor1(Double.valueOf(jTvalor1.getText()));
        calculos.setValor2(Double.valueOf(jTvalor2.getText()));
        jLresultado.setText("" + calculos.dividir());
    }//GEN-LAST:event_jBdividirActionPerformed

    private void jBporcentagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBporcentagemActionPerformed
        // TODO add your handling code here:
        calculos.setValor1(Double.valueOf(jTvalor1.getText()));
        calculos.setValor2(Double.valueOf(jTvalor2.getText()));
        jLresultado.setText("" + calculos.porcentagem());
    }//GEN-LAST:event_jBporcentagemActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBdividir;
    private javax.swing.JButton jBmultiplicar;
    private javax.swing.JButton jBporcentagem;
    private javax.swing.JButton jBsomar;
    private javax.swing.JButton jBsubtrair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLresultado;
    private javax.swing.JTextField jTvalor1;
    private javax.swing.JTextField jTvalor2;
    // End of variables declaration//GEN-END:variables
}
